CREATE TABLE IF NOT EXISTS "choredom_chore" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "choredom_chore_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"point_value" integer NOT NULL
);
--> statement-breakpoint
DROP TABLE "choredom_post";--> statement-breakpoint
ALTER TABLE "choredom_task" ALTER COLUMN "point_value" SET NOT NULL;